stages: 
      - build
image: docker:latest
services:
    - docker:dind
builder:
    stage: build
    script:
        - docker build -t $CI_REGISTRY/ret1/devops-netology/python-api:gitlab-$CI_COMMIT_SHORT_SHA .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY/ret1/devops-netology/python-api:gitlab-$CI_COMMIT_SHORT_SHA
    only: 
        - main
